# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bun-aarch64-darwin = {
    pname = "bun-aarch64-darwin";
    version = "1.3.14";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.14/bun-darwin-aarch64.zip";
      sha256 = "sha256-2LliIYKK1vl6x6wKt+lYcjQa92MAHogD6CZ2UsJlJiA=";
    };
  };
  bun-aarch64-linux = {
    pname = "bun-aarch64-linux";
    version = "1.3.14";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.14/bun-linux-aarch64.zip";
      sha256 = "sha256-on/7Y6gxA3WDbg1vZorhf6jY0YuIw3yCHGUzGXOhmjs=";
    };
  };
  bun-x86_64-darwin = {
    pname = "bun-x86_64-darwin";
    version = "1.3.14";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.14/bun-darwin-x64.zip";
      sha256 = "sha256-QYPfM3RiPlurMVxUfPoJdFM81FfYa3O2OfeoeXTNZjM=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "1.3.14";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.3.14/bun-linux-x64.zip";
      sha256 = "sha256-lR7iruhV8IWVruxiJSJqKY0/6oOj3NZGXAnLzN9+hI8=";
    };
  };
}
